import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/app/Navbar";
import Providers from "@/components/Providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`w-screen min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}>
                <Providers>
                    <Navbar />
                    <main className="relative pt-12 min-h-screen">
                        {children}
                    </main>
                </Providers>
            </body>
        </html>
    );
}
